name: nodal
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - ipython
  - isort
  - obspy
  - openpyxl
  - pip
  - pygmt
  - rioxarray
  - simplekml
  - utm
  - pip:
    - mat73
    - --editable ~/repos/infresnel
    - --editable .  # Installs packages specified in setup.py
