name: nodal
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cdsapi
  - cfgrib
  - colorcet
  - datashader
  - geopandas
  - ipython
  - isort
  - numba
  - obspy
  - openpyxl
  - pip
  - pooch
  - pygmt
  - rioxarray
  - simplekml
  - tqdm
  - pip:
    - imageio
    - mat73
    - multitaper
    - git+https://github.com/liamtoney/infresnel.git
    - --editable .  # Installs packages specified in setup.py
