name: nodal
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cdsapi
  - cfgrib
  - colorcet
  - ipython
  - isort
  - numba
  - obspy
  - openpyxl
  - pip
  - pooch
  - pygmt
  - rioxarray
  - simplekml
  - tqdm
  - pip:
    - mat73
    - --editable ${HOME}/repos/infresnel
    - --editable ${HOME}/work/python_util
    - --editable .  # Installs packages specified in setup.py
